import type { SupportedLocale } from './i18n'

export const INTERVIEW_ANALYSIS_I18N: Record<
  SupportedLocale,
  {
    systemMessage: string
    interviewTypes: {
      humanAssisted: string
      digitalHuman: string
    }
    interviewTypeExplanation: {
      humanAssisted: string
      digitalHuman: string
    }
    labels: {
      jobDescription: string
      requirements: string
      interviewTranscript: string
      conversationTurns: string
      candidateResponded: string
      questionsTotal: string
      validAnswers: string
      completionRate: string
      notAnswered: string
    }
    speechRecognitionNote: string
    conversationalGuidelines: string
    qaGuidelines: string
    jsonInstruction: string
  }
> = {
  en: {
    systemMessage:
      'You are an expert recruiter who provides thorough, fair, and insightful candidate evaluations. Your scoring should be objective and balanced, acknowledging both weaknesses and strengths. Good performers should receive appropriately high scores, while poor performers should receive fairly low scores. Return only valid JSON.',
    interviewTypes: {
      humanAssisted: 'AI-Assisted Human Interview',
      digitalHuman: 'Digital Human Interview',
    },
    interviewTypeExplanation: {
      humanAssisted: `【Interview Type】
This is a human-led interview with AI assistance. Focus on evaluating the candidate's interaction quality with the human interviewer.`,
      digitalHuman: `【Interview Type】
This is an AI digital human-led conversational interview. Focus on evaluating the candidate's performance and adaptability in an AI-guided conversation.`,
    },
    labels: {
      jobDescription: 'Job Description',
      requirements: 'Requirements',
      interviewTranscript: 'Interview Transcript',
      conversationTurns: 'conversation turns',
      candidateResponded: 'candidate responded',
      questionsTotal: 'questions total',
      validAnswers: 'valid answers',
      completionRate: 'Interview Completion Rate',
      notAnswered: '(Not answered or invalid answer)',
    },
    speechRecognitionNote:
      'Note: This transcript was auto-generated by speech recognition. Please ignore filler words and focus on the actual content of responses.',
    conversationalGuidelines: `TWO-LAYER SCORING SYSTEM:

=== LAYER 1: INTERVIEW PERFORMANCE (determines score & recommendation) ===
Score each dimension from 1-10:

1. RELEVANCE (30% weight): Does the candidate directly answer the questions asked?
   - 9-10: Every answer directly addresses the question with specific details
   - 7-8: Most answers are on-topic with minor tangents
   - 5-6: Some answers miss the point or are too generic
   - 3-4: Frequently off-topic or gives prepared/rehearsed answers unrelated to questions
   - 1-2: Consistently fails to answer what was asked

2. DEPTH (30% weight): Quality and depth of answers in this interview
   - 9-10: Demonstrates expert-level knowledge with concrete examples
   - 7-8: Shows solid understanding with real experience
   - 5-6: Basic knowledge, lacks depth or real-world examples
   - 3-4: Superficial understanding, mostly theoretical
   - 1-2: Little to no relevant knowledge shown

3. CLARITY (20% weight): Communication quality in this interview
   - 9-10: Crystal clear, well-structured, easy to follow
   - 7-8: Generally clear with good organization
   - 5-6: Understandable but could be more organized
   - 3-4: Confusing, jumps around, hard to follow
   - 1-2: Very poor communication, incoherent

4. ENGAGEMENT (20% weight): Active participation in this interview
   - 9-10: Highly interactive, asks good questions, builds on discussion
   - 7-8: Good participation, responds thoughtfully
   - 5-6: Passive but responsive
   - 3-4: Minimal interaction, one-word or rote answers
   - 1-2: Disengaged or unresponsive

TOTAL SCORE = (relevance × 3) + (depth × 3) + (clarity × 2) + (engagement × 2)

RECOMMENDATION (strictly determined by score):
- 80-100: strong_yes
- 65-79: yes
- 50-64: maybe
- 35-49: no
- 0-34: strong_no

=== LAYER 2: ABILITY PROFILE (for radar chart visualization) ===
Assess candidate's overall abilities (independent of Layer 1):
- technical_skills: Rate each skill mentioned (beginner/intermediate/advanced/expert)
- soft_skills: Rate communication, problem-solving, teamwork, professionalism (1-5 each)
- cultural_fit: Rate overall cultural fit (1-10)

Note: Layer 2 is for visualization only. It does NOT affect the score or recommendation.`,
    qaGuidelines: `TWO-LAYER SCORING SYSTEM:

=== LAYER 1: INTERVIEW PERFORMANCE (determines score & recommendation) ===
Score each dimension from 1-10:

1. RELEVANCE (30% weight): Does the candidate directly answer the questions asked?
   - 9-10: Every answer directly addresses the question with specific details
   - 7-8: Most answers are on-topic with minor tangents
   - 5-6: Some answers miss the point or are too generic
   - 3-4: Frequently off-topic or gives prepared/rehearsed answers unrelated to questions
   - 1-2: Consistently fails to answer what was asked

2. DEPTH (30% weight): Quality and depth of answers in this interview
   - 9-10: Demonstrates expert-level knowledge with concrete examples
   - 7-8: Shows solid understanding with real experience
   - 5-6: Basic knowledge, lacks depth or real-world examples
   - 3-4: Superficial understanding, mostly theoretical
   - 1-2: Little to no relevant knowledge shown

3. CLARITY (20% weight): Communication quality in this interview
   - 9-10: Crystal clear, well-structured, easy to follow
   - 7-8: Generally clear with good organization
   - 5-6: Understandable but could be more organized
   - 3-4: Confusing, jumps around, hard to follow
   - 1-2: Very poor communication, incoherent

4. ENGAGEMENT (20% weight): Active participation in this interview
   - 9-10: Highly interactive, asks good questions, builds on discussion
   - 7-8: Good participation, responds thoughtfully
   - 5-6: Passive but responsive
   - 3-4: Minimal interaction, one-word or rote answers
   - 1-2: Disengaged or unresponsive

TOTAL SCORE = (relevance × 3) + (depth × 3) + (clarity × 2) + (engagement × 2)

RECOMMENDATION (strictly determined by score):
- 80-100: strong_yes
- 65-79: yes
- 50-64: maybe
- 35-49: no
- 0-34: strong_no

=== LAYER 2: ABILITY PROFILE (for radar chart visualization) ===
Assess candidate's overall abilities (independent of Layer 1):
- technical_skills: Rate each skill mentioned (beginner/intermediate/advanced/expert)
- soft_skills: Rate communication, problem-solving, teamwork, professionalism (1-5 each)
- cultural_fit: Rate overall cultural fit (1-10)

Note: Layer 2 is for visualization only. It does NOT affect the score or recommendation.`,
    jsonInstruction: `Provide analysis in JSON format:
{
  "dimension_scores": {
    "relevance": {"score": 1-10, "notes": "specific observations"},
    "depth": {"score": 1-10, "notes": "specific observations"},
    "clarity": {"score": 1-10, "notes": "specific observations"},
    "engagement": {"score": 1-10, "notes": "specific observations"}
  },
  "score": number (MUST calculate: relevance×3 + depth×3 + clarity×2 + engagement×2),
  "recommendation": "strong_yes|yes|maybe|no|strong_no",
  "overall_assessment": "string",
  "strengths": ["string"],
  "weaknesses": ["string"],
  "red_flags": ["string"] (optional),
  "technical_skills": [{"skill": "string", "level": "beginner|intermediate|advanced|expert", "notes": "string"}],
  "soft_skills": [{"skill": "string", "rating": 1-5, "notes": "string"}],
  "cultural_fit": {"rating": 1-10, "notes": "string"}
}`,
  },
  zh: {
    systemMessage:
      '你是一位资深的招聘专家，能够提供全面、公正且有洞察力的候选人评估。你的评分应该客观平衡，既要指出不足，也要充分认可候选人的优势和潜力。对于表现良好的候选人，应该给予相应的高分；对于表现不佳的候选人，也要公正地给予较低分数。请仅返回有效的JSON格式，所有文本内容使用中文。',
    interviewTypes: {
      humanAssisted: 'AI辅助真人面试',
      digitalHuman: 'AI数字人面试',
    },
    interviewTypeExplanation: {
      humanAssisted: `【面试类型】
这是一次由真人主导、AI 辅助的面试。请重点评估候选人与真人面试官的互动质量。`,
      digitalHuman: `【面试类型】
这是一次由 AI 数字人主导的对话式面试。请重点评估候选人在 AI 引导对话中的表现与适应能力。`,
    },
    labels: {
      jobDescription: '岗位描述',
      requirements: '岗位要求',
      interviewTranscript: '面试记录',
      conversationTurns: '轮对话',
      candidateResponded: '候选人回应',
      questionsTotal: '问题总数',
      validAnswers: '有效回答',
      completionRate: '面试完成率',
      notAnswered: '（未回答或无效回答）',
    },
    speechRecognitionNote:
      '注意：该记录由语音识别自动生成，请忽略口头禅和填充词，重点关注回答的实际内容。',
    conversationalGuidelines: `双层评分体系：

=== 第一层：面试表现（决定总分与推荐）===
请对以下维度按 1-10 分打分：

1. 相关性（30%）：是否直接回答问题，紧扣提问要点？
2. 深度（30%）：回答的质量与深度，是否有具体经验与案例？
3. 清晰度（20%）：表达是否清晰、有结构、易理解？
4. 参与度（20%）：是否积极互动、能推动对话深入？

总分 = 相关性×3 + 深度×3 + 清晰度×2 + 参与度×2

推荐（严格按分数）：
- 80-100：strong_yes
- 65-79：yes
- 50-64：maybe
- 35-49：no
- 0-34：strong_no

=== 第二层：能力画像（用于雷达图，不影响总分）===
评估 technical_skills / soft_skills / cultural_fit。`,
    qaGuidelines: `双层评分体系：

=== 第一层：面试表现（决定总分与推荐）===
请对以下维度按 1-10 分打分：

1. 相关性（30%）：是否直接回答问题，紧扣提问要点？
2. 深度（30%）：回答的质量与深度，是否有具体经验与案例？
3. 清晰度（20%）：表达是否清晰、有结构、易理解？
4. 参与度（20%）：是否积极互动、能推动对话深入？

总分 = 相关性×3 + 深度×3 + 清晰度×2 + 参与度×2

推荐（严格按分数）：
- 80-100：strong_yes
- 65-79：yes
- 50-64：maybe
- 35-49：no
- 0-34：strong_no

=== 第二层：能力画像（用于雷达图，不影响总分）===
评估 technical_skills / soft_skills / cultural_fit。`,
    jsonInstruction: `请按 JSON 格式输出：
{
  "dimension_scores": {
    "relevance": {"score": 1-10, "notes": "具体观察"},
    "depth": {"score": 1-10, "notes": "具体观察"},
    "clarity": {"score": 1-10, "notes": "具体观察"},
    "engagement": {"score": 1-10, "notes": "具体观察"}
  },
  "score": number（必须计算：relevance×3 + depth×3 + clarity×2 + engagement×2）,
  "recommendation": "strong_yes|yes|maybe|no|strong_no",
  "overall_assessment": "string",
  "strengths": ["string"],
  "weaknesses": ["string"],
  "red_flags": ["string"]（可选）,
  "technical_skills": [{"skill": "string", "level": "beginner|intermediate|advanced|expert", "notes": "string"}],
  "soft_skills": [{"skill": "string", "rating": 1-5, "notes": "string"}],
  "cultural_fit": {"rating": 1-10, "notes": "string"}
}`,
  },
  es: {
    systemMessage:
      'Eres un reclutador experto que proporciona evaluaciones exhaustivas, justas e informativas. Tu puntuación debe ser objetiva y equilibrada. Devuelve solo JSON válido.',
    interviewTypes: {
      humanAssisted: 'Entrevista Humana Asistida por IA',
      digitalHuman: 'Entrevista con Humano Digital',
    },
    interviewTypeExplanation: {
      humanAssisted:
        '【Tipo de entrevista】\nEsta es una entrevista dirigida por un humano con asistencia de IA. Enfócate en la calidad de interacción con el entrevistador humano.',
      digitalHuman:
        '【Tipo de entrevista】\nEsta es una entrevista conversacional dirigida por un humano digital de IA. Enfócate en el desempeño y adaptabilidad del candidato.',
    },
    labels: {
      jobDescription: 'Descripción del Puesto',
      requirements: 'Requisitos',
      interviewTranscript: 'Transcripción de la Entrevista',
      conversationTurns: 'turnos de conversación',
      candidateResponded: 'candidato respondió',
      questionsTotal: 'preguntas en total',
      validAnswers: 'respuestas válidas',
      completionRate: 'Tasa de Finalización',
      notAnswered: '(No respondido o respuesta inválida)',
    },
    speechRecognitionNote:
      'Nota: Esta transcripción fue generada automáticamente. Ignora muletillas y enfócate en el contenido.',
    conversationalGuidelines: 'Usa el mismo sistema de puntuación de dos capas descrito en inglés.',
    qaGuidelines: 'Usa el mismo sistema de puntuación de dos capas descrito en inglés.',
    jsonInstruction: 'Responde en formato JSON siguiendo el esquema indicado en inglés.',
  },
  fr: {
    systemMessage:
      "Vous êtes un recruteur expert qui fournit des évaluations approfondies, justes et pertinentes. Retournez uniquement du JSON valide.",
    interviewTypes: {
      humanAssisted: 'Entretien Humain Assisté par IA',
      digitalHuman: 'Entretien avec Humain Numérique',
    },
    interviewTypeExplanation: {
      humanAssisted:
        "【Type d'entretien】\nEntretien mené par un humain avec assistance IA. Évaluez la qualité d'interaction avec le recruteur.",
      digitalHuman:
        "【Type d'entretien】\nEntretien conversationnel mené par un humain numérique IA. Évaluez la performance et l'adaptabilité du candidat.",
    },
    labels: {
      jobDescription: "Description du Poste",
      requirements: 'Exigences',
      interviewTranscript: "Transcription de l'Entretien",
      conversationTurns: 'tours de conversation',
      candidateResponded: 'candidat a répondu',
      questionsTotal: 'questions au total',
      validAnswers: 'réponses valides',
      completionRate: 'Taux de Complétion',
      notAnswered: '(Non répondu ou réponse invalide)',
    },
    speechRecognitionNote:
      "Note : cette transcription est générée automatiquement. Ignorez les mots de remplissage et concentrez-vous sur le contenu.",
    conversationalGuidelines: "Utilisez le même système de notation à deux couches décrit en anglais.",
    qaGuidelines: "Utilisez le même système de notation à deux couches décrit en anglais.",
    jsonInstruction: "Répondez en JSON en suivant le schéma indiqué en anglais.",
  },
}

